### ISSUE TITLE
Java 162 update return 404

### ISSUE THREAD

**Issue by praveen049** [andrewrothstein/ansible-java-oracle#1]
Hi
  The Java oracle role ( which i am using as part of spark role dependency) is failing as
fatal: [10.254.20.171]: FAILED! => {"changed": false, "dest": "/tmp/jre-8u162-linux-x64.tar.gz", "msg": "Request failed", "response": "HTTP Error 404: Not Found", "state": "absent", "status_code": 404, "url": "http://download.oracle.com/otn-pub/java/jdk/8u162-b12/0da788060d494f5095bf8624735fa2f1/jre-8u162-linux-x64.tar.gz"}

The update 162 seems not available anymore.

I have fixed this by moving to update 171 in defaults main.yml
---
# defaults file for java-oracle

# jre or jdk
java_oracle_prefix: jre

java_oracle_mirror: http://download.oracle.com/otn-pub/java/jdk
java_oracle_platform: linux-x64

java_oracle_ver:
  major: 8
  minor: 0
  patch: 171
  post_patch: b11
  uuid: '512cd62ec5174c3487ac17c61aaa89e8'
  checksums:
    jre:
      'linux-x64': sha256:d489c36c2b1c056f399fcd3893ee5d80da873ab7d5c73980a7b6cd8b87a6f6ba
    jdk:
      'linux-x64': sha256:b6dd2837efaaec4109b36cfbb94a774db100029f98b0d78be68c27bec0275982

Perhaps you can update the role for the Java version.

Thanks

**Comment by knservis** [comment]
Hi @andrewrothstein sent PR about this. I hope it's ok
