### ISSUE TITLE
With version 1.0.7 jre download link fails

### ISSUE THREAD

**Issue by achandel** [andrewrothstein/ansible-java-oracle#4]
FAILED! => {"changed": false, "dest": "/tmp/jre-8u172-linux-x64.tar.gz", "msg": "Request failed", "response": "HTTP Error 404: Not Found", "state": "absent", "status_code": 404, "url": "http://download.oracle.com/otn-pub/java/jdk/8u172-b11/a58eab1ec242421181065cdc37240b08/jre-8u172-linux-x64.tar.gz"}

**Comment by andrewrothstein** [comment]
oracle is not the best at keeping old versions of they binaries available. I upgraded the role to to 8u192.

**Comment by jagarcia29** [comment]
@andrewrothstein - Oracle has released a new version of Java 8 and the role is breaking once again. I did some digging around and it seems like Oracle requires you to log in before they will let you download any of their archived versions. You can try it yourself by attempting to download anything [here](https://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase8-2177648.html ).

I don't see any long-term solution besides updating the download URL to the latest version every time Oracle makes a new release. Do you think you could update it again?

Thanks in advance for your help!

**Comment by andrewrothstein** [comment]
updated and published to the galaxy as v1.1.3 with java 8u202.
