### ISSUE TITLE
JRE 8 Seems to Require Login Post April 2019 License Change

### ISSUE THREAD

**Issue by berney** [andrewrothstein/ansible-java-oracle#6]
Seems you need a login to download JRE8.
Also the URL seems to be `/otn/` now rather than `/otn-pub/`.

**Comment by andrewrothstein** [comment]
I think I'm going to switch my roles to using openjdk. Just added a role to that effect. Don't like the new Oracle license. They're headed in a more closed direction. I want to keep my roles as "hands free" as possible. I'm open to a PR that accepts as a var the authorization code u need/get from logging into they website.

**Comment by berney** [comment]
The auth seems complicated. I hope there's no compatibility issues with alternative implementations, I suspect a lot more people are going to make the switch so any compatibility issues will probably get sorted.
