### ISSUE TITLE
Failing checksum test

### ISSUE THREAD

**Issue by deanmaniatis** [andrewrothstein/ansible-java-oracle#7]
Hi,
I'm using latest Hadoop role from your ansible-galaxy repo and it fails at the JRE download checksum test with the following error. Any hints why would i get a different checksum?

```
TASK [andrewrothstein.java-oracle : download tgz...] *********************************************************
task path: /home/linaras/.ansible/roles/andrewrothstein.java-oracle/tasks/tgz.yml:10
fatal: [10.164.200.223]: FAILED! => {"changed": false, "msg": "The checksum for /tmp/jre-8u181-linux-x64.tar.gz did not match 0b26c7fcfad20029e6e0989e678efcd4a81f0fe502a478b4972215533867de1b; it was 80212f7748c2671b89b6085000717c747851db004409dce3bb97f3a2aeb91cdd."}
```

**Comment by berney** [comment]
Oracle changed the license, you can't download the JRE directly anymore. I presume what was downloaded was a web page redirecting you to login with an Oracle account before you can download the real JRE, hence why the checksum test is failing.

**Comment by deanmaniatis** [comment]
Hi, thanks for the reply. I came to the same conclusion shortly after commenting the "cleanup" task just to check the downloaded archive which was 5kb and couldn't even possibly be the intended file.
